#!/bin/bash

dirmngr </dev/null

echo "[archzfs]" >> /etc/pacman.conf
echo "Server = http://archzfs.com/\$repo/\$arch" >> /etc/pacman.conf

pacman-key -r 5E1ABF240EE7A126
pacman-key --lsign-key 5E1ABF240EE7A126

pacman -Syy --noconfirm archzfs-git

